using Schemorph.Provider.Postgres.Shadow;

namespace Schemorph.Provider.Postgres.Tests;

/// <summary>
/// Synthesis is proven by applying its output and re-diffing to empty — never
/// by reading it (the §6 withdrawal condition of the incremental plan: if this
/// stops converging on the corpus, ADR-0007 is re-evaluated on the spot).
/// </summary>
public class DdlSynthesisTests
{
    // The live schema, one release behind the desired one — drift in every
    // direction this slice claims: a column to add (with identity options), a
    // column to drop, a type change, a default change, a NOT NULL change, a
    // constraint to add, a table to create (PK + FK), a table to drop.
    private const string LiveV1 = """
        CREATE TABLE "Workspaces" (
            "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
            "Name" text NOT NULL,
            "Tier" text DEFAULT 'free',
            "Note" character varying(50),
            "Legacy" integer,
            CONSTRAINT "PK_Workspaces" PRIMARY KEY ("Id")
        );
        CREATE TABLE "Obsolete" ("x" integer);
        """;

    private const string DesiredV2 = """
        CREATE TABLE "Workspaces" (
            "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
            "Name" text NOT NULL,
            "Tier" text NOT NULL DEFAULT 'pro',
            "Note" text,
            "Seq" integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 5 START WITH 100),
            CONSTRAINT "PK_Workspaces" PRIMARY KEY ("Id"),
            CONSTRAINT "CK_Tier" CHECK ("Tier" IN ('free', 'pro'))
        );
        CREATE TABLE "Members" (
            "Id" uuid NOT NULL,
            "WorkspaceId" uuid NOT NULL,
            CONSTRAINT "PK_Members" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Members_Workspaces" FOREIGN KEY ("WorkspaceId")
                REFERENCES "Workspaces" ("Id") ON DELETE CASCADE
        );
        """;

    [SkippableFact]
    public async Task Applying_the_synthesized_script_converges_to_an_empty_diff()
    {
        await using var desiredSchema = await PgTestSchema.CreateAsync(DesiredV2);
        await using var liveSchema = await PgTestSchema.CreateAsync(LiveV1);

        var desired = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, desiredSchema.Name, normalizeSameSchemaReferences: true);
        var live = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, liveSchema.Name, normalizeSameSchemaReferences: true);

        var statements = DdlSynthesizer.Synthesize(liveSchema.Name, desired, live);
        Assert.NotEmpty(statements);

        // Embedded expression texts are unqualified (comparison-mode snapshots),
        // so the executor sets search_path — the contract the synthesizer states.
        await PgTestSchema.ExecuteAsync(
            $"SET search_path TO \"{liveSchema.Name}\";\n" + string.Join("\n", statements));

        var after = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, liveSchema.Name, normalizeSameSchemaReferences: true);
        var result = SnapshotComparer.Compare(desired, after);

        Assert.Empty(result.Changes);
        Assert.Empty(result.OutOfScope);
    }

    [SkippableFact]
    public async Task Synthesis_from_identical_schemas_is_empty()
    {
        // The synthesizer must agree with the comparer about what "equal" is —
        // a statement synthesized out of two equal snapshots would be drift
        // manufactured by the tool itself.
        await using var a = await PgTestSchema.CreateAsync(DesiredV2);
        await using var b = await PgTestSchema.CreateAsync(DesiredV2);

        var desired = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, a.Name, normalizeSameSchemaReferences: true);
        var live = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, b.Name, normalizeSameSchemaReferences: true);

        Assert.Empty(DdlSynthesizer.Synthesize(b.Name, desired, live));
    }
}
