namespace Schemorph.Provider.Postgres.Tests;

public class DesiredStateRendererTests
{
    private static PgTable Workspaces() => new(
        "vibebase_control", "Workspaces",
        Columns:
        [
            new PgColumn("Id", "uuid", NotNull: true, Default: "gen_random_uuid()"),
            new PgColumn("Name", "text", NotNull: true, Default: null),
            new PgColumn("CreatedAt", "timestamp with time zone", NotNull: true, Default: "now()"),
        ],
        Constraints:
        [
            new PgConstraint("PK_Workspaces", "PRIMARY KEY (\"Id\")"),
            new PgConstraint("CK_Workspaces_Status", "CHECK ((\"Status\" = ANY (ARRAY['active'::text, 'suspended'::text])))"),
        ],
        Indexes: [new PgIndex("IX_Workspaces_Name", "CREATE UNIQUE INDEX \"IX_Workspaces_Name\" ON vibebase_control.\"Workspaces\" USING btree (\"Name\")")]);

    [Fact]
    public void One_file_per_table_under_the_conventional_layout()
    {
        var files = DesiredStateRenderer.Render([Workspaces()]);

        var file = Assert.Single(files);
        Assert.Equal("tables/vibebase_control.Workspaces.sql", file.RelativePath);
    }

    [Fact]
    public void Every_identifier_is_quoted()
    {
        // Postgres folds unquoted identifiers to lower case, so a PascalCase
        // schema that renders unquoted does not round-trip. This is the same
        // defect that eliminated psqldef in the engine spike.
        var sql = DesiredStateRenderer.Render([Workspaces()])[0].Content;

        Assert.Contains("CREATE TABLE \"vibebase_control\".\"Workspaces\"", sql);
        Assert.Contains("\"Id\" uuid NOT NULL", sql);
        Assert.DoesNotContain("CREATE TABLE vibebase_control", sql);
    }

    [Fact]
    public void Defaults_and_nullability_render_verbatim_from_the_catalog()
    {
        var sql = DesiredStateRenderer.Render([Workspaces()])[0].Content;

        Assert.Contains("\"Id\" uuid NOT NULL DEFAULT gen_random_uuid()", sql);
        Assert.Contains("\"Name\" text NOT NULL,", sql);
        Assert.Contains("\"CreatedAt\" timestamp with time zone NOT NULL DEFAULT now()", sql);
    }

    [Fact]
    public void Constraints_are_attached_to_their_table_file()
    {
        // Each file is a complete, self-applicable desired state — the same rule
        // the SQL Server renderer follows by folding constraints into the table.
        var sql = DesiredStateRenderer.Render([Workspaces()])[0].Content;

        Assert.Contains(
            "ALTER TABLE \"vibebase_control\".\"Workspaces\" ADD CONSTRAINT \"PK_Workspaces\" PRIMARY KEY (\"Id\");",
            sql);
        Assert.Contains("ADD CONSTRAINT \"CK_Workspaces_Status\" CHECK", sql);
    }

    [Fact]
    public void Index_statements_are_emitted_as_the_catalog_gave_them()
    {
        var sql = DesiredStateRenderer.Render([Workspaces()])[0].Content;

        Assert.Contains("CREATE UNIQUE INDEX \"IX_Workspaces_Name\"", sql);
        Assert.EndsWith(";\n", sql.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void No_TSql_batch_separators_leak_into_Postgres_output()
    {
        var sql = DesiredStateRenderer.Render([Workspaces()])[0].Content;

        Assert.DoesNotContain("GO", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void An_embedded_quote_in_an_identifier_is_doubled()
    {
        var table = new PgTable("public", "we\"ird", [new PgColumn("c", "text", false, null)], [], []);

        var sql = DesiredStateRenderer.Render([table])[0].Content;

        Assert.Contains("\"we\"\"ird\"", sql);
    }

    [Fact]
    public void A_table_with_no_columns_still_renders_valid_sql()
    {
        // Postgres allows zero-column tables; rendering must not emit a dangling
        // comma or an empty parenthesis pair that fails to parse.
        var table = new PgTable("public", "Empty", [], [], []);

        var sql = DesiredStateRenderer.Render([table])[0].Content;

        Assert.Contains("CREATE TABLE \"public\".\"Empty\" ();", sql);
    }

    [Fact]
    public void A_generated_column_renders_as_generated_not_as_default()
    {
        // The catalog stores the generation expression in the DEFAULT slot;
        // rendering it as DEFAULT is wrong SQL (cycle-76 reader gap).
        var table = new PgTable("public", "Prices",
            [new PgColumn("Total", "numeric", NotNull: true, Default: null,
                GeneratedAs: "(\"Price\" * \"Qty\")")],
            [], []);

        var sql = DesiredStateRenderer.Render([table])[0].Content;

        Assert.Contains("\"Total\" numeric NOT NULL GENERATED ALWAYS AS ((\"Price\" * \"Qty\")) STORED", sql);
        Assert.DoesNotContain("DEFAULT", sql);
    }

    [Theory]
    [InlineData(PgIdentity.Always, "GENERATED ALWAYS AS IDENTITY")]
    [InlineData(PgIdentity.ByDefault, "GENERATED BY DEFAULT AS IDENTITY")]
    public void An_identity_column_renders_its_identity_clause(PgIdentity identity, string clause)
    {
        var table = new PgTable("public", "T",
            [new PgColumn("Id", "bigint", NotNull: true, Default: null, Identity: identity)],
            [], []);

        var sql = DesiredStateRenderer.Render([table])[0].Content;

        Assert.Contains($"\"Id\" bigint NOT NULL {clause}", sql);
        Assert.DoesNotContain("(", sql.Split(clause)[1].Split('\n')[0]);   // no empty option list
    }

    [Fact]
    public void Non_default_identity_options_survive_the_round_trip()
    {
        var table = new PgTable("public", "T",
            [new PgColumn("Id", "integer", NotNull: true, Default: null,
                Identity: PgIdentity.ByDefault, IdentityOptions: "INCREMENT BY 5 START WITH 100")],
            [], []);

        var sql = DesiredStateRenderer.Render([table])[0].Content;

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 5 START WITH 100)", sql);
    }

    [Fact]
    public void A_file_name_never_carries_identifier_characters_the_file_system_rejects()
    {
        // The SQL content must keep the identifier exact; only the file NAME is
        // sanitized (a quoted identifier like we"ird is a valid Postgres name
        // and an invalid Windows file name).
        var table = new PgTable("public", "we\"ird", [new PgColumn("c", "text", false, null)], [], []);

        var file = DesiredStateRenderer.Render([table])[0];

        Assert.DoesNotContain("\"", Path.GetFileName(file.RelativePath));
        Assert.StartsWith("tables/public.we_ird-", file.RelativePath);
        Assert.Contains("\"we\"\"ird\"", file.Content);   // content untouched
    }
}
