using Schemorph.Provider.Postgres.Shadow;

namespace Schemorph.Provider.Postgres.Tests;

/// <summary>
/// The invariant every slice must add to its own corpus (dev plan §3): apply
/// the desired state, then diff again, and the plan is empty. The corpus keeps
/// the spike's killer shapes — quoted PascalCase, <c>CHECK (… IN …)</c> (which
/// the engine stores as <c>= ANY (ARRAY[…])</c>), a same-schema FK, an
/// expression index — because these are exactly where text comparison without
/// engine normalization never converges (the SQL Server limitation this
/// provider must not replicate).
/// </summary>
public class RediffEmptyTests
{
    private const string Corpus = """
        CREATE TABLE "Workspaces" (
            "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
            "Name" text NOT NULL,
            "Tier" text NOT NULL DEFAULT 'free',
            "Seq" integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 5 START WITH 100),
            CONSTRAINT "PK_Workspaces" PRIMARY KEY ("Id"),
            CONSTRAINT "CK_Tier" CHECK ("Tier" IN ('free', 'pro'))
        );
        CREATE TABLE "Members" (
            "Id" uuid NOT NULL,
            "WorkspaceId" uuid NOT NULL,
            CONSTRAINT "PK_Members" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Members_Workspaces" FOREIGN KEY ("WorkspaceId")
                REFERENCES "Workspaces" ("Id") ON DELETE CASCADE
        );
        CREATE UNIQUE INDEX "IX_Workspaces_Lower" ON "Workspaces" (lower("Name"));
        """;

    [SkippableFact]
    public async Task Applying_the_rendered_state_and_rediffing_yields_an_empty_comparison()
    {
        await using var live = await PgTestSchema.CreateAsync(Corpus);
        var rendered = DesiredStateRenderer.Render(
            await CatalogReader.ReadTablesAsync(PgTestSchema.ServerUrl!, live.Name));

        await using var shadow = await ShadowSchema.CreateAsync(PgTestSchema.ServerUrl!);
        await shadow.ApplyAsync(
            rendered.Select(f => f.Content).ToList(), sourceSchema: live.Name);

        // Both sides in comparison mode: same-schema FK targets, index ON
        // clauses and regclass literals render UNQUALIFIED, so the shadow and
        // the live schema produce byte-equal canonical texts.
        var desired = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, shadow.Name, normalizeSameSchemaReferences: true);
        var actual = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, live.Name, normalizeSameSchemaReferences: true);

        var result = SnapshotComparer.Compare(desired, actual);

        Assert.Empty(result.Changes);
        Assert.Empty(result.OutOfScope);
    }

    [SkippableFact]
    public async Task A_real_difference_still_surfaces_through_the_same_normalized_read()
    {
        // Normalization must erase schema-location noise and NOTHING else.
        await using var live = await PgTestSchema.CreateAsync(Corpus);
        var rendered = DesiredStateRenderer.Render(
            await CatalogReader.ReadTablesAsync(PgTestSchema.ServerUrl!, live.Name));

        await using var shadow = await ShadowSchema.CreateAsync(PgTestSchema.ServerUrl!);
        await shadow.ApplyAsync(
            rendered.Select(f => f.Content).ToList(), sourceSchema: live.Name);
        await PgTestSchema.ExecuteAsync(
            $"ALTER TABLE \"{shadow.Name}\".\"Members\" ADD COLUMN \"JoinedAt\" timestamptz NOT NULL DEFAULT now();");

        var desired = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, shadow.Name, normalizeSameSchemaReferences: true);
        var actual = await CatalogReader.ReadTablesAsync(
            PgTestSchema.ServerUrl!, live.Name, normalizeSameSchemaReferences: true);

        var change = Assert.Single(SnapshotComparer.Compare(desired, actual).Changes);
        Assert.Equal(new Core.Providers.RawChange("Change", "Table", "Members"), change);
    }
}
