namespace Schemorph.Provider.Postgres;

/// <summary>
/// The catalog as Schemorph reads it — plain data, no engine types, no
/// connection. Everything downstream of the reader works on this, which is what
/// keeps rendering testable without a database.
/// </summary>
/// <summary>How a column's value is generated by the engine, if at all.</summary>
public enum PgIdentity
{
    None,
    /// <summary>GENERATED ALWAYS AS IDENTITY.</summary>
    Always,
    /// <summary>GENERATED BY DEFAULT AS IDENTITY.</summary>
    ByDefault,
}

/// <param name="DataType">
/// The engine's own rendering (<c>format_type</c>), not a mapping of ours. The
/// engine is the normalizer (ADR-0007); re-spelling types here would reintroduce
/// exactly the text-comparison drift that decision exists to avoid.
/// </param>
/// <param name="Default">
/// Plain DEFAULT expression (<c>pg_get_expr</c>). Null for generated columns —
/// the catalog stores their expression in the same slot, but rendering it as
/// DEFAULT would be wrong SQL, so the reader routes it to
/// <paramref name="GeneratedAs"/> instead.
/// </param>
/// <param name="GeneratedAs">
/// The generation expression of a <c>GENERATED ALWAYS AS (…) STORED</c> column.
/// </param>
/// <param name="IdentityOptions">
/// Sequence options of an identity column, already rendered (e.g.
/// <c>START WITH 100 INCREMENT BY 5</c>) — null when every option is the
/// engine default, so the common case renders clean.
/// </param>
public sealed record PgColumn(
    string Name,
    string DataType,
    bool NotNull,
    string? Default,
    PgIdentity Identity = PgIdentity.None,
    string? GeneratedAs = null,
    string? IdentityOptions = null);

/// <param name="Definition">
/// From <c>pg_get_constraintdef</c> — the engine's canonical form, e.g.
/// <c>PRIMARY KEY ("Id")</c>. Emitted verbatim for the same reason.
/// </param>
public sealed record PgConstraint(string Name, string Definition);

/// <param name="CreateStatement">
/// From <c>pg_indexes.indexdef</c> — already a complete CREATE INDEX statement.
/// </param>
public sealed record PgIndex(string Name, string CreateStatement);

public sealed record PgTable(
    string Schema,
    string Name,
    IReadOnlyList<PgColumn> Columns,
    IReadOnlyList<PgConstraint> Constraints,
    IReadOnlyList<PgIndex> Indexes);
